spring:
  application:
    name: Semantic Sardine
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: mrjacktung/mradermacher-llamax3-8b-alpaca-gguf
      log-requests: true
      temperature: 0
      log-responses: true

logging:
  level:
    dev.langchain4j: DEBUG